on: [push, repository_dispatch, workflow_dispatch]

env:
  TARGET_PACKAGE: "@github-packages-examples/npm-publish"

jobs:

  create-and-install:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        registry: ["https://npm.pkg.github.com", "https://npm.pkg.github.com/github-packages-examples"]

    steps:
      - uses: actions/setup-node@v1
        with:
          scope: github-packages-examples
          registry-url: ${{ matrix.registry }}

      - name: Create a package called @${{ github.repository }}
        run: npm init --scope ${{ github.repository_owner }} -y

      - name: Add index.js to package
        run: echo 'require("${{ env.TARGET_PACKAGE }}").sayHello()' > index.js

      - name: Install a package
        run: npm install ${{ env.TARGET_PACKAGE }}
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Execute package
        run: npx .
